lib/network.rb

Linux systems may not be configured to ping broadcast services. So, I have made a change to enable the system to check that.

A check for broadcast ping

---

bin/bettercap

`OptionParser` comes with a pretty good help menu out of the box, so now bettercap has a `--help` flag. Some of the longer help items will be wrapped if you are running in a narrow window, but it's a start.
One concern I have is that the help menu cannot be printed without being run as root – perhaps it would be helpful to allow certain commands to run without requiring elevated privileges.
I was also seeing exceptions being thrown during the call to `remove_const`, so I added a rescue statement to prevent it from taking down the program.
(Also, fixed a couple of typos.)

Add help flag

---

lib/bettercap/network.rb

The method #is_ip in the Network class checks for IPv4 addresses only. In OSX, it will often grab the IPv6 address in this loop as it is listed as a second default iface when running `netstat` and will exit false on is_ip?(gw) on line 46. This will exit once it finds the first valid default IPv4 address. 
May be an issue with other environments?

Fixed common error with OSX iface detection

---

lib/bettercap/context.rb

Rubygems has all stable versions of bettercap,
let's use that server instead of github which
might contain development versions.
Signed-off-by: Felipe Balbi <balbif@gmail.com>

bettercap: check version on rubygems

---

lib/bettercap/firewalls/linux.rb

In Linux, iptables are being cleared when adding every port redirection, so when proxy-https is enabled, the first rule (for http) is added after flushing, but when adding the second rule (for https), iptables are flushed again.
Finally, when exiting, bettercap tries to delete the port redirection rules but http redirection rule doesn't exist. This actually stops the normal flow, and leaves the https redirection rule enabled (!).
```
iptables: No chain/target/match by that name.
/var/lib/gems/2.1.0/gems/bettercap-1.1.4/lib/bettercap/shell.rb:17:in `execute': Error, executing iptables -t nat -D PREROUTING -i wlan0 -p TCP --dport 80 -j REDIRECT --to 8080 (BetterCap::Error)
from /var/lib/gems/2.1.0/gems/bettercap-1.1.4/lib/bettercap/firewalls/linux.rb:45:in `del_port_redirection'
from …
```

remove flush in add_port_redirection

---

bin/bettercap
lib/bettercap/context.rb

Hi everyone, I tought it might be useful to extend the tool in order to be able to use it in a scenario where a gateway is not present or is not part of the MITM. I was performing some tests on a small network and I needed to perform a MITM attack between two PCs on the same LAN without involving the current gateway. So I slightly modified bettercap in order to be able to specify the gateway address in the command line (I'm not a skilled ruby programmer, hope I'm not shaking too much the code). 
Technically calling it gateway is not correct, since ... well ... is not a gateway :), but I coulnd't come up with a better name\description without rewriting everywhere for refactoring the name "gateway" with a more general one.
What do you think?

Added manual gateway 

---

bettercap.gemspec

Bettercap is failing to run in BlackArch as it's installed from gemspec which seemed to be missing the network_interface gem.

Added missing dependency network_interface to gemspec.

---

lib/bettercap/factories/parser.rb
lib/bettercap/factories/spoofer.rb
lib/bettercap/network.rb

On at least one platform (Linux), const_get with a fully qualified name
was not working as expected.

Fix bug in Spoofer::get_by_name

---

lib/bettercap/sniffer/parsers/httpauth.rb

Invalid argument number when calling StreamLogger.log_raw in http auth parser
> [W] wrong number of arguments (2 for 3)

fix bug in http auth sniffer

---

lib/bettercap/firewalls/linux.rb

Ruby has proper File IO class which abstracts accesses
to files. We don't need to spawn a shell just to call
echo/cat to write/read contents of files.
Signed-off-by: Felipe Balbi <balbi@kernel.org>

bettercap: firewalls: linux: avoid shell for file access

---

lib/bettercap/sniffer/parsers/mpd.rb

Sniff clear text credentials from Music Player Daemon (MPD) connections.

Add sniffer/parsers/MPD

---

lib/bettercap/sniffer/parsers/rlogin.rb

Sniff usernames from BSD Rlogin connections.
Sadly, in the event the server prompts for a password, the password won't be recorded by this parser as the password is transferred later in the stream.

Add sniffer/parsers/RLOGIN

---

lib/bettercap/sniffer/parsers/snpp.rb

Sniff clear text credentials from Simple Network Paging Protocol (SNPP) connections.
Not sure if you want to add this. Tested with a fake server (netcat) due to lack of a test server.
Implemented based on RFC:
* https://tools.ietf.org/html/rfc1861
* https://en.wikipedia.org/wiki/Simple_Network_Paging_Protocol

Add sniffer/parsers/SNPP

---

lib/bettercap/firewalls/base.rb
lib/bettercap/firewalls/openbsd.rb

Both systems use PF, so there is very little new code --- the new file (openbsd.rb) is a direct copy of the OSX.rb file, with just the class name and a comment changed. In practice, we could just create a firewall object instance simply by cloning Firewalls::OSX in the OpenBSD case, but creating a separate file seems cleaner and inviting for less trouble if/when feature support diverges in the future.

Add support for OpenBSD

---

lib/bettercap/monkey/packetfu/utils.rb
lib/bettercap/network/arp_reader.rb

It took me 2 hours to notice that you had cloned utils.rb from PacketFu...anyway, this is now functional to the point of doing being able to do both ARP and ICMP-based spoofing

I think this is full support for OpenBSD

---

README.md

Consider the possibility that people are not running the latest version of Kali rolling.

Make sure Kali is updated before installing Bettercap

---

lib/bettercap/firewalls/bsd.rb

Since `.enable` will never raise an error we can safely use rescue syntax for `.del_port_redirection`

Syntax sugar for bettercap/firewalls

---

lib/bettercap/proxy/http/modules/injecthtml.rb

JS and CSS have a file option, but HTML was missing.

Add an --html-file PATH option

---

lib/bettercap.rb

Optimized require statements to remove redundant gem dependencies.
Updated “’s and some spacing changes using rubocop as a guide.
Changed unless filename.include?('proxy/http/modules') to a next
statement instead.

Remove redundant requires, minor update to syntax using rubocop

---

bettercap.gemspec
lib/bettercap/options/core_options.rb

There was no rainbow option. Fixing that before someone’s feelings gets
hurt.
It look's awesome:
It's a pretty easy thing to add. I really like it.
Ettercap doesn't have a rainbow option. This could be a **another** awesome point for bettercap. I also just _really_ like this. I really want this. It's fine if I don't get this ... Plus, it's optional, so it doesn't necessarily hurt anyone. And since it's pretty trivial to implement, we can take it out if it does end up being some crazy disaster. Which I don't think it will be. 
There's no real disadvantages. You can argue some practicalities, but, like, it's beautiful. 
Lolize just hooks to standard out / standard error and gives a rainbow output for bettercap when the `-R` or `--rainbows` option is used. 
Yeah. I just really like this.

Fix missing rainbow option

---

lib/bettercap/context.rb
lib/bettercap/discovery/agents/ndp.rb
lib/bettercap/firewalls/linux.rb
lib/bettercap/monkey/packetfu/utils.rb
lib/bettercap/network/ndp_reader.rb
lib/bettercap/network/network.rb
lib/bettercap/network/target.rb
lib/bettercap/network/validator.rb
lib/bettercap/options/core_options.rb
lib/bettercap/options/spoof_options.rb
lib/bettercap/proxy/http/proxy.rb
lib/bettercap/shell.rb
lib/bettercap/spoofers/ndp.rb

Depends on PR [ https://github.com/packetfu/packetfu/pull/160 ] on PacketFu. This patch supports MitM attacks on IPv6 endpoints with Javascript Injection ( possibly all modules, not tested for others yet ). However not all user options are implemented, as in the initial IPv4 version.
It is executed with the command: sudo bettercap -t VICITIM_IPV6 --proxy --proxy-module injectjs --js-file PATH_TO_JS_FILE --no-ssltrip . 
The PacketFu Library with the Neighbor Discovery PR is also required.

[WIP] Ipv6 support 

---

lib/bettercap/sniffer/parsers/teamtalk.rb

Sniff clear text authentication credentials from [BearWare TeamTalk](http://bearware.dk/) connections.
The server supports TCP and UDP on port 10333. This parser has been tested only on TCP.

Add sniffer/parsers/TeamTalk

---

lib/bettercap/spoofers/arp.rb

Attacking wireless clients form a wired device resulted in a DoS for the attacker upon hitting CTRL-C. This is because the broadcast address was used during the restoration of the arp table.
This commit fixes it.

Fix re-arp issue on tp-link and other routers.

---

lib/bettercap/context.rb

There were just too many decimals.

One digit of precision is good enough.

---

lib/bettercap/sniffer/parsers/asterisk.rb

Sniff clear text authentication credentials from Asterisk Call Manager connections on port 5038/tcp.

Add sniffer/parsers/Asterisk

---

lib/bettercap/sniffer/parsers/wol.rb

This PR adds a [Wake-on-LAN](https://en.wikipedia.org/wiki/Wake-on-LAN) packet and authentication parser.
* Supports WOL on UDP ports 0, 7 and 9
* Does not support ether-wake which uses Ethertype 0x0842
Example output:
```
[local > *:discard] [WOL] mac=11:22:33:44:55:66 password=none
[local > *:discard] [WOL] mac=11:22:33:44:55:66 password=11223344
[local > *:discard] [WOL] mac=11:22:33:44:55:66 password=112233445566
```

Add sniffer/parsers/wol

---

lib/bettercap/sniffer/parsers/asterisk.rb
lib/bettercap/sniffer/parsers/dhcp.rb
lib/bettercap/sniffer/parsers/dict.rb
lib/bettercap/sniffer/parsers/https.rb
lib/bettercap/sniffer/parsers/mpd.rb
lib/bettercap/sniffer/parsers/redis.rb
lib/bettercap/sniffer/parsers/rlogin.rb
lib/bettercap/sniffer/parsers/snmp.rb
lib/bettercap/sniffer/parsers/snpp.rb
lib/bettercap/sniffer/parsers/teamtalk.rb
lib/bettercap/sniffer/parsers/teamviewer.rb
lib/bettercap/sniffer/parsers/whatsapp.rb

Minor code cleanup; rescues from `on_packet` method in sniffers, rather than using `begin; rescue` blocks.
Keeps the code closer to the left margin.
Results in slightly smaller file sizes.

Rescue from on_packet method in sniffers

---

lib/bettercap/sniffer/parsers/asterisk.rb
lib/bettercap/sniffer/parsers/dhcp.rb
lib/bettercap/sniffer/parsers/dict.rb
lib/bettercap/sniffer/parsers/mpd.rb
lib/bettercap/sniffer/parsers/post.rb
lib/bettercap/sniffer/parsers/redis.rb
lib/bettercap/sniffer/parsers/rlogin.rb
lib/bettercap/sniffer/parsers/snmp.rb
lib/bettercap/sniffer/parsers/snpp.rb
lib/bettercap/sniffer/parsers/teamtalk.rb
lib/bettercap/sniffer/parsers/teamviewer.rb
lib/bettercap/sniffer/parsers/url.rb

Minor code cleanup; uses `return unless` guard clause syntax in sniffers, rather than traditional `if` conditional blocks.
Keeps the code closer to the left margin.
Results in slightly smaller file sizes.

Use return unless guard clause in sniffers

---

bin/bettercap
docs/intro.md
lib/bettercap/proxy/http/modules/redirect.rb
lib/bettercap/sniffer/parsers/nntp.rb

I hear using HTTPS hinders MitM attacks.

Use HTTPS links in documentation

---

lib/bettercap/sniffer/parsers/hsrp.rb

This PR adds a HSRP packet and authentication parser, spaghetti edition.
Unfortunately, after pretty much completing this module, and debugging why some packets were missed, I realised that [PacketFu supports HSRP packets natively](http://www.rubydoc.info/github/todb/packetfu/PacketFu/HSRPHeader) and was swallowing the headers, causing `pkt.payload` to contain only the optional HSRP packet body.
Fortunately (for me, at least) there seems to be a bug in PacketFu which means I didn't totally waste my time implementing this parser from scratch.
The following packet capture is not detected as HSRP by PacketFu for whatever reason:
* https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=hsrp-and-ospf-in-LAN
Furthermore, the `hsrp` utility generates packets which are also not …

Add sniffer/parser/hsrp

---

lib/bettercap/spoofers/hsrp.rb

This PR adds a spoofer for [Hot Standby Router Protocol (HSRP)](https://en.wikipedia.org/wiki/Hot_Standby_Router_Protocol).
**Note: This spoofer will not work with the latest version of PacketFu.** You'll need to [patch PacketFu](https://github.com/packetfu/packetfu/pull/186) to detect all HSRP traffic properly.
In theory, this attack allows commandeering the role of an active router in an existing HSRP group, by advertising as a router with higher priority than the Active router in the HSRP group, resulting in a Man-in-the-Middle scenario.
This spoofer has been implemented based on assumptions and conclusions drawn from [RFC2281](https://tools.ietf.org/html/rfc2281).
I've tested with Wireshark and confirmed all the pieces operate as I expect, but haven't verified on a HSRP network. It's …

Add HSRP Spoofer

---

lib/bettercap/spoofers/mac.rb

This PR adds a [MAC flooding](https://en.wikipedia.org/wiki/MAC_flooding) spoofer.
Effectively the same as using dsniff's `macof -i <interface>` - but with Bettercap :)

Add MAC Spoofer

---

lib/bettercap/sniffer/parsers/ospf.rb

This PR adds an [OSPF](https://en.wikipedia.org/wiki/Open_Shortest_Path_First) packet and authentication parser.
This may be a little too chatty on OSPF networks. Easily fixed by `return`ing if the `AuthType` is `null (0)`.
Tested with pcaps:
* https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=hsrp-and-ospf-in-LAN
* https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=ospf.cap
* https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=ospf-md5.cap
* http://packetlife.net/captures/ospf%20over%20gre%20tunnel.cap  -- (fails due to GRE tunnel headers)
* http://packetlife.net/captures/ospf%20simple%20password%20authentication.cap
* http://packetlife.net/captures/ICMP_over_L2TPv3_Pseudowire.pcap.cap
* …

Add sniffer/parser/ospf

---

lib/bettercap/sniffer/parsers/ntp.rb

This PR adds a [Network Time Protocol (NTP)](https://en.wikipedia.org/wiki/Network_Time_Protocol) packet and authentication parser.
* Supports NTP version 4
* Supports IPv4
* Supports MD5 authentication
* Does not support IPv6
* Does not support NTP version 3
* Does not support SHA1 authentication
It turns out the NTP protocol is a mess (no offense, Dr. Mills) and I got bored with it quickly.
As far as I can tell, there's nothing in the header to indicate whether authentication digest is present. There are no delimiters or length fields from which to easily calculate the offset of the authentication data. As a result, the entire packet (of which there are several packet types of variable length) needs to be parsed before identifying the presence of authentication data which is tacked on …

Add sniffer/parser/NTP

---

lib/bettercap/proxy/http/modules/injectcss.rb
lib/bettercap/proxy/http/modules/injecthtml.rb
lib/bettercap/proxy/http/modules/injectjs.rb

When using the http proxy modules (injectcss, injectjs, and injecthtml) you can independently limit the number of times the injection occurs via the --css-max, --js-max, and --html-max options.

Add a 'maximum number of times to inject' option.
