- bettercap.gemspec
- bin/bettercap
- lib/bettercap.rb
- lib/bettercap/base/ifirewall.rb
- lib/bettercap/base/ispoofer.rb
- lib/bettercap/context.rb
- lib/bettercap/discovery/icmp.rb
- lib/bettercap/factories/firewall_factory.rb
- lib/bettercap/factories/parser_factory.rb
- lib/bettercap/factories/spoofer_factory.rb
- lib/bettercap/firewalls/linux.rb
- lib/bettercap/firewalls/osx.rb
- lib/bettercap/httpd/server.rb
- lib/bettercap/logger.rb
- lib/bettercap/network.rb
- lib/bettercap/proxy/module.rb
- lib/bettercap/proxy/proxy.rb
- lib/bettercap/proxy/request.rb
- lib/bettercap/proxy/response.rb
- lib/bettercap/sniffer/parsers/base.rb
- lib/bettercap/target.rb
Well, the codebase works (even though I didn't run it yet actually :P) but it's a little mess. Indentation is not consistent (what about writing a `CONTRIBUTE` with some guidelines for contributors?), methods contain dozens of LoC that need to be splitted up in many little and private methods to make clear what they do and so on.
I tried to fix what I could and leave some comments here and there. Unfortunately atm I have no time to read the whole codebase to make a better PR, so I hope this one could be enough useful to make bettercap better.
I also suggest you to use rubocop, it's pretty awesome.
> Refactor to make something more ruby-esque

- lib/bettercap/network.rb
First of all, what a fantastic tool! Thank you so much for your work on this. :+1: 
I ran into a bug when targeting the whole network (`sudo bettercap -X`) on Mac OSX 10.10.4. Sometimes it works beautifully:
```
[I] Targeting the whole subnet 192.168.1.0..192.168.1.255 ...
[I] Network discovery thread started.
[I] Searching for alive targets ...
[I] Getting gateway 192.168.1.254 MAC address ...
[I]   Gateway : 192.168.1.254 ( e8:33:81:ee:fd:e0 )
[I]   Local : 192.168.1.123 ( 60:03:08:91:ba:42 )
[I] Starting ARP spoofer ...
[I] Starting sniffer ...
[I] Collected 3 total targets.
[I]   192.168.1.78 : 4c:b1:99:3d:fd:2 ( Apple )
[I]   192.168.1.85 : e4:25:e7:a:2f:8f ( Apple )
[I]   192.168.1.126 : cc:3d:82:2:26:78 ( Intel Corporate )
[W] Aquired 3 new targets.
[192.168.1.85:64504 > …
```
> Fix capture stream bug on Mac OSX

- Gemfile
- Gemfile.lock
With this we can use bundler to install dependencies
during development.
Signed-off-by: Felipe Balbi <balbif@gmail.com>
> bettercap: add a Gemfile

- bin/bettercap
- lib/bettercap/target.rb
Using comma to separate the addresses, e.g. `bettercap -X -T 192.168.1.2,192.168.1.3`
> Target multiple addresses

- bin/bettercap
- lib/bettercap/context.rb
This pull request improves version checking a little bit by shuffling responsibilities around and making sure that callers can trust (and make assumptions about) what we return.
> Improve version check

- lib/bettercap/spoofers/arp.rb
https://github.com/evilsocket/bettercap/issues/56
> Fixing capturing on ArpSpoofer

- CONTRIBUTING.md
I guess running the command without sudo-ing is legit.
> Makes sudo-ing an optional step

- lib/bettercap/sniffer/parsers/nntp.rb
Sniff clear text credentials from NNTP connections.
> Add sniffer/parsers/NNTP

- lib/bettercap/sniffer/parsers/dict.rb
Sniff clear text credentials from DICT connections.
> Add sniffer/parsers/DICT

- lib/bettercap/sniffer/parsers/redis.rb
Sniff clear text credentials from Redis (RESP) connections.
> Add sniffer/parsers/Redis

- lib/bettercap/network/protos/snmp.rb
- lib/bettercap/sniffer/parsers/snmp.rb
SNMPv1 protocol parser.
At the moment only version, community string and not PDU.
Tested with snmpd daemon on Ubuntu server.
Todo:
- add SNMPv1 PDU structure
- add SNMPv2 support
Please feel free to modify it!
> SNMPv1 protocol parser

- lib/bettercap/firewalls/base.rb
- lib/bettercap/firewalls/openbsd.rb
You didn't read the last line on my response. Please pull in...not sure how "elseif" was in there to begin with.
> "elseif" -> "elsif"

- lib/bettercap/proxy/http/modules/injectcss.rb
- lib/bettercap/proxy/http/modules/injecthtml.rb
- lib/bettercap/proxy/http/modules/injectjs.rb
Fixes #234 
Tested
Example file with this issue [here](https://gist.github.com/esarafianou/98ad9e2589e547980af0c9901638c31d)
The sequence backslash - backtick is in lines 4713 and 4714.
> Use sub! with block to avoid strange sub! behaviour when data contain s  the sequence backslash-backtick

- lib/bettercap/network/packet_queue.rb
- lib/bettercap/network/protos/base.rb
- lib/bettercap/network/protos/teamviewer.rb
- lib/bettercap/network/servers/httpd.rb
- lib/bettercap/network/target.rb
Refactored if statements to return early, they look more concise now
> rescue syntax and if statement refactoring

- lib/bettercap/options/options.rb
> Show the checkmark instead of the word true.

- bin/bettercap
Fixed the issue as discussed [here](https://github.com/evilsocket/bettercap/issues/334#issuecomment-266840796).
> Prioritize root privilege check

- lib/bettercap/monkey/packetfu/utils.rb
This monkey patch enables the utility of [ https://github.com/evilsocket/bettercap/pull/374#issuecomment-277435535 ].
Depends on PacketFu pull request [ https://github.com/packetfu/packetfu/pull/160 ] . Changes on that PR may be requested, hence this patch is not the final form of PacketFu. This may result in minor changes in Bettercap too. Will be fixed as soon as the PacketFu branch is merged.
> Add PacketFu monkey patch for ndp

- lib/bettercap/context.rb
Minor fix to last ipv6 changes. Single target ipv6 injection now works again.
> Fix context ipv6 detection

- lib/bettercap/discovery/agents/mdns.rb
- lib/bettercap/network/network.rb
This PR adds a discovery agent using mDNS service discovery.
I'm not sure how useful this will be. But now it exists.
> Add mDNS Discovery Agent

- lib/bettercap/discovery/agents/upnp.rb
- lib/bettercap/network/network.rb
This PR adds a discovery agent using UPnP SSDP.
I'm not sure how useful this will be. But now it exists.
> Add UPnP SSDP Discovery Agent

- lib/bettercap/discovery/agents/wsd.rb
- lib/bettercap/network/network.rb
This PR adds a discovery agent using WS-Discovery.
I'm not sure how useful this will be. But now it exists.
> Add WSD Discovery Agent

- lib/bettercap/sniffer/parsers/bfd.rb
This PR adds a [Bidirectional Forwarding Detection (BFD)](https://en.wikipedia.org/wiki/Bidirectional_Forwarding_Detection) packet and authentication parser.
I tried testing it with some software but didn't have much luck:
* https://github.com/dyninc/OpenBFDD  (Doesn't support authentication)
* http://sourceforge.net/projects/bfd-server/  (Appears to be broken)
* http://bfd-server.cvs.sourceforge.net/viewvc/bfd-server/  (Appears to be broken)
Tested with the [Wireshark Sample Captures](https://wiki.wireshark.org/SampleCaptures):
* https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=bfd-raw-auth-simple.pcap
* https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=bfd-raw-auth-md5.pcap
* https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=g …
> Add sniffer/parser/bfd

- README.md
This PR makes very small edits to the README to improve the readability.
- add code fences
> README: Markdown, language

- lib/bettercap/sniffer/parsers/radius.rb
This PR adds a [RADIUS](https://en.wikipedia.org/wiki/RADIUS) packet and authentication parser.
Tested with pcaps:
* https://supportforums.cisco.com/sites/default/files/legacy/3/1/9/64913-radius.pcap
* http://packetlife.net/captures/RADIUS.cap
Unfortunately it doesn't work with the [Wireshark Sample Captures](https://wiki.wireshark.org/SampleCaptures) as the packet appears to be malformed (Betercap skips all 19 packets). However, the packet contents are still available. Perhaps this should be looked into a bit further?
* https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=bfd-raw-auth-simple.pcap
Sample output:
```
[I] [SNIFFER] Reading packets from /pentest/mitm/bettercap/64913-radius.pcap ...
[192.168.10.12 > 192.168.10.11:radius] [RADIUS] access-request Code=1 …
```
> Add sniffer/parser/radius
